title: &title "kurz und scherzlos."

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

locale: "de-DE"
timezone: "Europe/Berlin"

name: ""
description: &description "Ein kleines Schreibprojekt. Kurzgeschichten aller Art und Poesie mit Reimen. Nicht immer mit Reimen. Und nicht immer scherzlos; manchmal aber schon."

url: "https://kurzundscherzlos.de"
repository: "kurzundscherzlos/kurzundscherzlos.github.io"

# head_scripts:
#   - 
# footer_scripts:
#   - 

# breadcrumbs: true
search: true
search_full_content: true

og_image: "/assets/images/profile.png"

social:
  links:
    - "https://instagram.com/kurzundscherzlos"
    - "https://reddit.com/u/kurzundscherzlos"

# analytics:
#   provider: "google-gtag"
#   google:
#     tracking_id: "???"
#     anonymize_ip: false # default

author:
  name     : *title
  avatar   : "/assets/images/profile.png"
  bio      : *description
  location : "In einem Städtchen, nördlich der Alpen." 
  links:
    - label: "web"
      icon: "fas fa-fw fa-link"
      url: "https://kurzundscherzlos.de"
    - label: "instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/kurzundscherzlos"
    - label: "reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://reddit.com/u/kurzundscherzlos"

# footer:
#   links:
#     - label: "web"
#       icon: "fas fa-fw fa-link"
#       url: "https://kurzundscherzlos.de"
#     - label: "instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/kurzundscherzlos"
#     - label: "reddit"
#       icon: "fab fa-fw fa-reddit"
#       url: "https://reddit.com/u/kurzundscherzlos"
# _data/ui-text.yml >> follow_label >> Follow:

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
#       author_profile: true
#      sidebar:
#        nav: "links"

plugins:
  - jekyll-archives # for breadcrumb
  - jekyll-feed
  - jekyll-include-cache